[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "https://jahtkqvekhdjwoflatpg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impha3RrcXZla2hkandvZmxhdHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0Mzg0MzcsImV4cCI6MjA1MDAxNDQzN30.8wqGOBZR7jRJ5mlVJEH_VQpDl1JzUhUWvyHJTYJfmQc"

[[plugins]]
  package = "@netlify/plugin-nextjs"
